if [[ "${OSTYPE}" == darwin* ]]; then
  export BROWSER='open'
fi

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# if [[ -z "$LANG" ]]; then
#   eval "$(locale)"
# fi

export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

typeset -gU \
  fpath     \
  cdpath    \
  mailpath  \
  manpath manpath_original \
  path path_original
typeset -gUT INFOPATH infopath

cdpath=(
  .
  ~
)

infopath=(
  $HOME/usr/share/info
  /usr/local/share/info
  /usr/share/info
)

manpath=(
  $HOME/usr/share/man
  $manpath
)

path=(
  ./node_modules/.bin
  ../node_modules/.bin
  ../../node_modules/.bin
  $HOME/usr/{bin,sbin}
  $HOME/.local/{bin,sbin}
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
)

export LESS='-F -g -i -M -R -S -w -X -z-4'
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [ -z $XDG_CONFIG_HOME ] && [ -d $HOME/.config ]; then
  export XDG_CONFIG_HOME=$HOME/.config
fi

if [ -d $HOME/projects ]; then
  export PROJECT_HOME=$HOME/projects
  cdpath=($cdpath $PROJECT_HOME)
fi

if [ -d $PROJECT_HOME/go ]; then
  export GOPATH=$PROJECT_HOME/go
  export GOBIN=$GOPATH/bin
  path=($GOBIN $path)
  cdpath=($cdpath $GOPATH)
fi

if [ -d $HOME/.nvm ]; then
  export NVM_DIR=$HOME/.nvm
fi

export HOMEBREW_NO_ANALYTICS=1
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=1
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

path_original=($path)
manpath_original=($manpath)
