# zmodload zsh/zprof

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

MYZSHDIR="${ZDOTDIR:-$HOME}/.myzsh"
MYZSH_PREZTO_REPO="${PROJECT_HOME}/prezto"

zstyle ':prezto:load' pmodule-dirs "${MYZSHDIR}/modules"
source "${MYZSH_PREZTO_REPO}/init.zsh"
typeset -U pmodules

zstyle ':prezto:module:editor' 'key-bindings' 'vi'
zstyle ':prezto:module:editor' 'dot-expansion' 'yes'
zstyle ':prezto:module:prompt' 'theme' 'monai'
zstyle ':prezto:module:utility' 'correct' 'no'
zstyle ':prezto:module:utility:ls' 'color' 'yes'
zstyle ':prezto:module:utility:make' 'color' 'yes'
zstyle ':prezto:module:python:virtualenv' 'initialize' 'no'
zstyle ':prezto:module:syntax-highlighting' 'color' 'yes'

pmodules=(
  'environment'
  'terminal'
  'editor'
  'history'
  'directory'
  'utility'
  'my-completion'
  'completion'

  'git'
  'osx'
  'history-substring-search'
  'my-spectrum'
  'my-theme'
  'prompt'
  'fasd'
  'archive'

  'my-utils'
  'my-stub'
  'my-keybindings'
  'my-aliases'
)

pmodload "${pmodules[@]}"

zplug 'zdharma/fast-syntax-highlighting'
zplug 'zsh-users/zsh-history-substring-search'
zplug 'Tarrasch/zsh-autoenv'
zplug "${HOME}/.zshrc.local", from:local
zplug "${HOME}/.iterm2_shell_integration.zsh", from:local

zplug load
