# zmodload zsh/zprof

BREW_PREFIX=$(brew --prefix)

ZPLUG_HOME="${BREW_PREFIX}/opt/zplug"
source "$ZPLUG_HOME/init.zsh"

MYZSH_HOME="${ZDOTDIR:-$HOME}/myzsh"
MYZSH_PREZTO_REPO="${PROJECT_HOME}/prezto"

zstyle ':prezto:load' pmodule-dirs "${MYZSH_HOME}/modules"
source "${MYZSH_PREZTO_REPO}/init.zsh"

zstyle ':prezto:module:editor' 'key-bindings' 'vi'
zstyle ':prezto:module:editor' 'dot-expansion' 'yes'
zstyle ':prezto:module:prompt' 'theme' 'monai'
zstyle ':prezto:module:utility' 'correct' 'no'
zstyle ':prezto:module:utility:ls' 'color' 'yes'
zstyle ':prezto:module:utility:make' 'color' 'yes'
zstyle ':prezto:module:python' 'conda-init' 'yes'
zstyle ':prezto:module:python:virtualenv' 'initialize' 'no'
zstyle ':prezto:module:syntax-highlighting' 'color' 'yes'

typeset -U pmodules
pmodules=(
  'environment'
  'terminal'
  'editor'
  'history'
  'directory'
  'utility'

  'git'
  'archive'

  'my-completion'
  'completion'

  'osx'
  'history-substring-search'
  'my-spectrum'
  'my-theme'
  'prompt'
  'fasd'

  'my-utils'
  'my-stub'
  'my-keybindings'
  'my-aliases'
  'my-iterm2'
)

pmodload "${pmodules[@]}"

zplug "zdharma-continuum/fast-syntax-highlighting"
zplug "Tarrasch/zsh-autoenv"
zplug "conda-incubator/conda-zsh-completion"
zplug "${ZDOTDIR:-$HOME}/.zshrc.local", from:local

zplug load
