MYZSHDIR="${ZDOTDIR:-$HOME}/.myzsh"

if [ -d "${PROJECT_HOME}/prezto" ]; then
  ZGEN_PREZTO_REPO="${PROJECT_HOME}/prezto"
fi

source "${MYZSHDIR}/vendor/zgen/zgen.zsh"

if ! zgen saved; then
  echo "Creating a zgen save"

  ZGEN_PREZTO_LOAD_DEFAULT=0

  zgen prezto editor       key-bindings  'vi'
  zgen prezto editor       dot-expansion 'yes'
  zgen prezto prompt       theme         'mytheme'
  zgen prezto utility:ls   color         'yes'
  zgen prezto utility:make color         'yes'
  zgen prezto syntax-highlighting  color 'yes'

  zgen prezto

  zgen prezto environment
  zgen prezto terminal
  zgen prezto editor
  zgen prezto history
  zgen prezto directory
  zgen prezto utility
  zgen prezto completion

  zgen prezto git

  zgen prezto osx
  zgen prezto syntax-highlighting
  zgen prezto history-substring-search
  zgen prezto prompt
  zgen prezto fasd

  zgen load "${MYZSHDIR}/modules/checks"
  zgen load "${MYZSHDIR}/modules/bootstrap"
  zgen load "${MYZSHDIR}/modules/keybindings"
  zgen load "${MYZSHDIR}/modules/spectrum"
  zgen load "${MYZSHDIR}/modules/mytheme"
  zgen load "${MYZSHDIR}/modules/aliases"
  zgen load "${MYZSHDIR}/modules/work-vpn"

  zgen save
fi

module_aliases_init
module_mytheme_init
module_keybindings_init

unsetopt CORRECT

if [ -f "${HOME}/.zshrc.local" ]; then
  source "${HOME}/.zshrc.local"
fi

if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then
  source "${HOME}/.iterm2_shell_integration.zsh"
fi
